export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_CHARACTERS_ERROR = "GET_CHARACTERS_ERROR";
export const SELECT_CHARACTER = "SELECT_CHARACTER";
export const SELECT_CHARACTER_ERROR = "SELECT_CHARACTER_ERROR";
export const SET_DEFAULT_PAGE = "SET_DEFAULT_PAGE";
export const SET_DEFAULT_PAGE_ERROR = "SET_DEFAULT_PAGE_ERROR";
export const SET_COUNT = "SET_COUNT";
